[package]
name = "ethereum-cli-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3", features = ["full"] }
structopt = "0.3"
tokio = { version = "1.40.0", features = ["full"] }
k256 = "0.11"  # k256 for secp256k1 key generation
sha3 = "0.10"  # For Keccak256 hashing
